### ISSUE TITLE
Configure, check and test all 3 I2C buses on EM2

### ISSUE THREAD

**Issue by RobertK66** [RobertK66/obc_1769_core#24]
- Enable all 4 sidepanel I2C buses and configre them (to use 100kHz at this time)
- write testcode to address external slaves

also see discussions here: #23

**Comment by kodsurf** [comment]
During initialization of LPC_I2C

![image](https://user-images.githubusercontent.com/66519643/172618775-89a1f4d1-7059-47c9-9a21-82d433117948.png)

I enabled switches 

which should activate LPC_I2C2 on A and B sides
![image](https://user-images.githubusercontent.com/66519643/172619036-5595d67f-9df2-4af7-bbf1-55e71f405952.png)

![image](https://user-images.githubusercontent.com/66519643/172619719-804903e3-4c14-49fb-a472-7e4e2a8ac96e.png)


Then I checked pinning_climb.h
![image](https://user-images.githubusercontent.com/66519643/172620029-cfd2c319-84e2-4ee6-9413-15243118df84.png)

All those switches are by default initialized with **HIGH** value.    

Meaning that all switches are enabled by default ? 



However the strange thing that I noticed : 

![image](https://user-images.githubusercontent.com/66519643/172620801-42a7a3b5-cff8-451a-aa40-9cc9b5f8f942.png)

If I manually set those switches to LOW  -  I2C still works (with wrong bytes)

**Comment by RobertK66** [comment]
Remark: You can test this (switch every Enable Pin) with my hw_check command:

| 'h'     | \<pinIdx\> \<mode\>       | sets an GPIO pin to mode (0: initVal, 1: high, 2: low, 3: slow blink, 4: fast osz.)                            |

The Pin Idx for the 4 I2C EN pins are: 

	PINIDX_I2C_A_EN  31
	PINIDX_I2C_D_EN  32
	PINIDX_I2C_C_EN  33
	PINIDX_I2C_B_EN  42

**Comment by kodsurf** [comment]
After latest remark regarding enabling C/D in  pinning_climbobc.h : 

I2C works correctly on every sidepanel.

Switches also work as expected.
