### ISSUE TITLE
RadTest II: Readout sensor values

### ISSUE THREAD

**Issue by RobertK66** [RobertK66/obc_1769_core#33]
output  - the sensor vals every x seconds.

**Comment by kodsurf** [comment]
![image](https://user-images.githubusercontent.com/66519643/183869154-577950fc-bc45-4068-ae7e-630fc7da5bc2.png)
By using this in layer 3sensor ?

readJob.rx_data should be printed to debug uart with system events string every 10 seconds ?

**Comment by kodsurf** [comment]
https://github.com/RobertK66/obc_1769_core/pull/36/commits/eea7990b273b370638fc188713a1e64ca7635e75

Is this what was meant for read sensor values ?

why not combine and continue with it in issue32 ?

**Comment by RobertK66** [comment]
Yes this should be ok. 
you mean to add it to https://github.com/RobertK66/obc_1769_core/tree/feature/issue32 branch and together with #36 pull request? Yes seems feasible because ;-).

**Comment by RobertK66** [comment]
fixed with #32
