### ISSUE TITLE
dev branch project is not compilable git clone

### ISSUE THREAD

**Issue by kodsurf** [RobertK66/obc_1769_core#44]
After git clone and submodules init

![image](https://user-images.githubusercontent.com/66519643/188629900-9ec160ed-002a-4a7f-913c-7a5dd866affa.png)

Project remains uncompiliable due to folder structure of ado_chip_175x_6x
![image](https://user-images.githubusercontent.com/66519643/188629803-628345f3-d10d-4ca2-8db1-bf9d3efb85f8.png)

To make project compilable I have to manually copy files from ado_chip_175x_6x folder. But this way git references are removed for ado project.

@RobertK66  Could you please look into structure of ado_chip folders so that whole OBC thing becomes instantly compiliable after git clone of obc_1769_core ?

Or possibly I do something wrong with git initialization ? 

Problem is that we get folder inside a folder with "ado_chip_175x_6x"
![image](https://user-images.githubusercontent.com/66519643/188630920-60643e70-975e-4435-b48f-6bf3f3028f26.png)

**Comment by kodsurf** [comment]
![image](https://user-images.githubusercontent.com/66519643/188631709-cb7bc4ec-1436-4738-8d25-6bd8dc34c817.png)


If manually copy ado files - it creates mess with untracked files for git

**Comment by kodsurf** [comment]
https://github.com/RobertK66/ado-chip-175x-6x/commit/66bce532e3781dd6291068f80021379024f23d97

This commit with CRC8 checksum functions is not on ado dev branch after clonning  repo


Strange .....

**Comment by kodsurf** [comment]
Changes from the commit 

https://github.com/RobertK66/ado-chip-175x-6x/commit/66bce532e3781dd6291068f80021379024f23d97

are not listed anywhere on ado dev branch !!! 

I manually added changes based on diff of commit. (and all looks good and compiliable)  But changes are not on git repo ! Veeery strange ..

**Comment by RobertK66** [comment]
Hi, sorry I started to write up some Doku about this submodule/checkout issue(s). Unfortunately I am not ready yet. I try to look into this tomorrow afternoon. Quick hint: Submodule (and 'Update Submodule) always refers to a single commit (should be good enough for you), BUT you can have the eclipse to 'sit' on a branch and checkout, if you (mainly its me ;-)) want to be able to develop and commit in lib module developer branch. Again I did not fully understand Eclipse client here but hope to get it sorted out later this week .. (I am available for Skype/Teams earliest Thursday, sorry....)

**Comment by RobertK66** [comment]
Stil working on the doku point for that....

**Comment by RobertK66** [comment]
I am now thinking of re-join the ado code into the obc_core code repository again....
(When I introduced the ado lib repository being an external repository and using this submodule thing, I had the idea that I will use it for different hardware projects with this CPU. As this is no longer the case with me, rejoining the code without submodule will be simple way for all to avoid this confusions.....)

**Comment by RobertK66** [comment]
I will do this next time we change or fix something in the ado lib code.
