### ISSUE TITLE
Create python script for orbital position prediction based on TLE

### ISSUE THREAD

**Issue by kodsurf** [RobertK66/obc_1769_core#47]
1)  TLE can be obtained by API

https://celestrak.org/NORAD/elements/gp.php?CATNR=25544&FORMAT=JSON

CATNR is ID of object in NORAD database

Object ID can be searched by the name using 
https://celestrak.org/satcat/search.php

Example : 

![image](https://user-images.githubusercontent.com/66519643/192546072-344c68c0-8aa0-49a1-a4a3-c7be78a218dc.png)

![image](https://user-images.githubusercontent.com/66519643/192546136-dc38ee1d-0aff-4153-9441-9ab40a2c7593.png)

substitute CARNR with PEGASUS ID : 

https://celestrak.org/NORAD/elements/gp.php?CATNR=42784&FORMAT=JSON

To obtain TLE of PEGASUS 

JSON
![image](https://user-images.githubusercontent.com/66519643/192546489-5896f830-caad-4424-a3e6-b5b8e606cc7f.png)

Or text

https://celestrak.org/NORAD/elements/gp.php?CATNR=42784&FORMAT=TLE

Output of simple HTTP GET request is 

![image](https://user-images.githubusercontent.com/66519643/192546837-3edc3096-bac0-49bc-90fc-24551fa8d1d4.png)

3 lines of strings. 

2) Capture those strings with python  (using curl http request)

And use : https://rhodesmill.org/pyephem/    

pyephem to calculate object possition (lat/lon/alt)  

Example : 
https://space.stackexchange.com/questions/4211/calculate-satellite-coordinates-from-tle-data

![image](https://user-images.githubusercontent.com/66519643/192547777-629b1897-cb32-4119-8162-d796738d1b86.png)

3) Use obtained lat,lon,alt ( and possible other data)

to create NMEA messages and print them to UART in a loop over time.

**Comment by kodsurf** [comment]
![image](https://user-images.githubusercontent.com/66519643/199042067-35dc9041-f51c-4142-ac12-04bd9e6a355e.png)


I added python script to simulate NMEA over orbit: https://github.com/RobertK66/obc_1769_core/commit/9c10894b416563b53adac0c0dfe166f4c7dabbe6

currently only for RMC message (will add another messages latter)

Looks ok but some unnessesary bytes received 
![image](https://user-images.githubusercontent.com/66519643/199042940-0783a2d4-f066-455c-9526-e324b99051a7.png)


--------------------------------------------------------------------------------
Update : aaaah this is "SysEvent" that checksum is wrong


![image](https://user-images.githubusercontent.com/66519643/199055743-73219dde-a14b-4c19-8368-964d2c215b69.png)

**Comment by kodsurf** [comment]
I struggle to understand how OBC NMEA parser and checksum calculation works


Example : I take a valid nmea message from 
https://orolia.com/manuals/VSP/Content/NC_and_SS/Com/Topics/APPENDIX/NMEA_GGAmess.htm
`"$GPGGA,123519.00,4807.038,N,01131.000,E,1,08,0.9,545.4,M,-164.0,M,,,,*47"`

Then I simply print out this message to COM port in the loop every 1s
![image](https://user-images.githubusercontent.com/66519643/199071106-662eb49d-c31a-460f-953a-ddfdf5d734a4.png)


What I receive on OBC is SysEvent String 
![image](https://user-images.githubusercontent.com/66519643/199071293-486dd5c7-388a-498f-9c7d-dd3648e6f1ed.png)

Why so ?

**Comment by kodsurf** [comment]
![image](https://user-images.githubusercontent.com/66519643/199323379-434aee3f-0f2d-458e-9f08-b1023372199b.png)


looks ok to me

https://github.com/RobertK66/obc_1769_core/commit/afa6182b956470684ed9892adeaead80ffd5bbe1

**Comment by kodsurf** [comment]
Only one thing left before I mark this python task as completed. 

![image](https://user-images.githubusercontent.com/66519643/199710736-454f1d4f-12cc-4454-a01d-edf492a9bf47.png)


With UTC timestamp that I supply for RMC message - I never reach  line 348 because  day < 1


I compile RMC message according to https://orolia.com/manuals/VSP/Content/NC_and_SS/Com/Topics/APPENDIX/NMEA_RMCmess.htm

![image](https://user-images.githubusercontent.com/66519643/199711342-04cad1ae-f35e-41ad-972e-9983586021da.png)

example of MY  string of NMEA RMC message

![image](https://user-images.githubusercontent.com/66519643/199711806-4bda2c5e-487e-4643-8bc0-e41d18650c0b.png)


Maybe this is not what OBC RMC parser expects ?

This is how I compile UTC string

input : 
yy - year (2022)
mon - month (11)
dd - date (3)
hh - hours (6)
mm -min (30)
ss - sec (5)
![image](https://user-images.githubusercontent.com/66519643/199712132-f472bb67-ac31-4421-9cb8-2c6ef040587e.png)



I checked OBC code 

![image](https://user-images.githubusercontent.com/66519643/199712703-01c6a03b-9d3a-42dd-ab0b-23ffad5b6175.png)



Looks like It is the same format that I supply.  But why is then day is wrong ?

**Comment by kodsurf** [comment]
Error is in date compilation of RMC message in python script.

"1102022" - WRONG

Correct format is ddmmyy - 03112022 ( or 3112022???)


What if it is first January?
01012023 or 112023

**Comment by kodsurf** [comment]
http://www.ae.utexas.edu/courses/ase389p7/projects/svatek/commands/RMC.html


Jevgeni please use Google before posting something stupid on issues.

Correct nmea message format with description is given at link above.

3.11.2022 is 031122

**Comment by kodsurf** [comment]
![image](https://user-images.githubusercontent.com/66519643/199785966-b8e25fdb-c82a-4af9-9f55-1825de555412.png)

https://github.com/RobertK66/obc_1769_core/commit/350f1099ea445e6fe7cfdec55f9cdce1ad13262f


I fixed date compilation in RMC message. Now everything works correctly as it seems with RMC parser of OBC.

**Comment by RobertK66** [comment]
Is the Script available somewhere?
You could share it in the tool folder, if you want.....

**Comment by kodsurf** [comment]
It is on feature/gps-integrate 

Utilities/python scripts

**Comment by RobertK66** [comment]
I will keep only the long lat values in OBC code and integrate this into develop without the debug stuff....
