### ISSUE TITLE
Checksum calculation for NMEA message parser does not work properly

### ISSUE THREAD

**Issue by kodsurf** [RobertK66/obc_1769_core#53]
Either I do something wrong, or 

![image](https://user-images.githubusercontent.com/66519643/199240354-a6f28f10-7673-4c46-ba98-cd1a2a41403e.png)

Those checksum cases does not do what they are expected to do. 

I had to manually turn off checsum check in order to proccessing function to be executed : https://github.com/RobertK66/obc_1769_core/commit/5c1a7d711af5fe2c5be69769a102eca3c48a1f8a

P.S : This is how I calculate checksum for autogenerated NMEA string : https://electronics.stackexchange.com/questions/214278/generating-hexadecimal-checksum-for-a-nmea-pmtk-message

If I take example NMEA message : $GPGGA,115739.00,4158.8441367,N,09147.4416929,W,4,13,0.9,255.747,M,-32.00,M,01,0000*6E

(with valid checksum from google  )  - Original dev branch NMEA parser still gives an error.

**Comment by kodsurf** [comment]
https://github.com/RobertK66/obc_1769_core/commit/7c087acd96c415e94a92e56667582c03c48987e7

Check summ is now ok... There was no problem with checksum.  Its just stupid me. But I solve it

**Comment by kodsurf** [comment]
But there is something even more stupid that I have discovered accidently. 

I stupidly left some int r =4 ;     for some reasons I dont remember and forgot to delete it. 
![image](https://user-images.githubusercontent.com/66519643/199604625-a5a0008d-e3b1-43fa-a191-12fb7de3db8d.png)


The thing is ....  when I tried to cleanup the code after checksum problem cleared up - I decided to delete all rubbish from code .... 

BUT WHEN I DELETE STUPID int r=4;

I get ... Hard fault . And not instantly, after arround 10-20 sec of parser working ...

![image](https://user-images.githubusercontent.com/66519643/199605051-3535644d-0240-4b1e-ac09-57b2963a71bd.png)

LAST_STARTED_MODULE = 3 


.... what a ....

**Comment by RobertK66** [comment]
Not sure what your status is here ;-)
Checksum calculation is/was ok !?
Another hardfault, which is somehow not related Or maybe with the usage of String output here ....

**Comment by kodsurf** [comment]
Sorry no problem there .... 

It was just me stupid. 

Resolved

**Comment by RobertK66** [comment]
No reason to apologize. I was just asking. Thats what Issues are for (initiate communication to learn something about the issue).
